import { LoveUniverseData } from '../../shared/models/love-universe-data.model';
import { ImportantDate } from '../../shared/models/important-date.model';

const seededAt = new Date().toISOString();

export const DEFAULT_DATA: LoveUniverseData = {
  version: '1.0.0',
  updatedAt: seededAt,
  settings: {
    activeTheme: 'dark-romantic',
    languageMode: 'en',
    animationsEnabled: true,
    musicEnabled: false,
    onboardingCompleted: false,
  },
  coupleProfile: {
    coupleSpaceName: 'Arova Space',
    partnerADisplayName: 'Partner A',
    partnerBDisplayName: 'Partner B',
    importantDate: undefined,
    favoriteSharedActivity: undefined,
    relationshipIntention: undefined,
    updatedAt: seededAt,
  },
  users: [
    {
      id: 'user-owner',
      username: 'owner',
      passcode: '1234',
      displayName: 'Partner A',
      role: 'admin',
      lastLoginAt: undefined,
    },
    {
      id: 'user-partner',
      username: 'partner',
      passcode: '1234',
      displayName: 'Partner B',
      role: 'partner',
      lastLoginAt: undefined,
    },
  ],
  memories: [
    {
      id: 'mem-001',
      title: 'Sample First Memory',
      description:
        'A generic shared moment placeholder for testing the memories page in a fresh install.',
      date: seededAt.slice(0, 10),
      category: 'firsts',
      mood: 'warm',
      visibleToPartner: true,
      isFavorite: true,
      privateNote: 'Admin-only placeholder note. Replace this only in a private personal copy.',
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      id: 'mem-002',
      title: 'Private Memory Placeholder',
      description:
        'A generic hidden memory used to confirm that partner visibility rules still work.',
      date: seededAt.slice(0, 10),
      category: 'deep',
      mood: 'reflective',
      visibleToPartner: false,
      isFavorite: false,
      privateNote: 'Placeholder private note for admin visibility testing.',
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      id: 'mem-003',
      title: 'Shared Laugh Placeholder',
      description:
        'A light sample memory that keeps the public demo friendly without using real personal details.',
      date: seededAt.slice(0, 10),
      category: 'funny',
      mood: 'bright',
      visibleToPartner: true,
      isFavorite: false,
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
  ],
  reasons: [
    {
      id: 'rsn-001',
      title: 'Sample reason to appreciate your partner',
      body:
        'This is generic placeholder copy for the reasons page. Replace it with personal content only in a private copy.',
      category: 'love',
      order: 1,
      isSecret: false,
      isFavorite: true,
      reactions: [],
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      id: 'rsn-002',
      title: 'Sample reason about trust',
      body:
        'A neutral demo reason that helps test sorting, favorite state, and detail routing.',
      category: 'trust',
      order: 2,
      isSecret: false,
      isFavorite: false,
      reactions: [],
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      id: 'rsn-003',
      title: 'Private reason placeholder',
      body:
        'This generic hidden reason exists only to test admin-only and owner-only visibility.',
      category: 'choose-you',
      order: 3,
      isSecret: true,
      isFavorite: false,
      reactions: [],
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
  ],
  letters: [
    {
      id: 'ltr-001',
      title: 'Open Letter Placeholder',
      body:
        'This is a generic sample letter for testing the public letter detail view. Add real words only in a private personal copy.',
      category: 'reassurance',
      isLocked: false,
      isFavorite: true,
      visibleToPartner: true,
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      id: 'ltr-002',
      title: 'Locked Letter Placeholder',
      body:
        'This placeholder body is hidden from Partner B while the letter is locked.',
      category: 'future',
      isLocked: true,
      isFavorite: false,
      visibleToPartner: true,
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      id: 'ltr-003',
      title: 'Hidden Letter Placeholder',
      body:
        'This generic hidden letter exists to verify admin-only and owner-only letter access.',
      category: 'miss-me',
      isLocked: false,
      isFavorite: false,
      visibleToPartner: false,
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
  ],
  moods: [],
  dailyQuestionAnswers: [],
  checkIns: [],
  songs: [
    {
      id: 'song-001',
      title: 'Demo Track Placeholder',
      artist: 'Generic Demo Artist',
      mood: 'missing-you',
      isFavorite: true,
      sourceName: 'Local placeholder',
      license: 'No audio file included',
      attribution: 'Preview unavailable until you add a safe local or licensed audio source.',
      createdAt: seededAt,
    },
    {
      id: 'song-002',
      title: 'Quiet Moment Placeholder',
      artist: 'Generic Demo Artist',
      mood: 'need-reassurance',
      isFavorite: false,
      sourceName: 'Local placeholder',
      license: 'No audio file included',
      attribution: 'Preview unavailable until you add a safe local or licensed audio source.',
      createdAt: seededAt,
    },
  ],
  challenges: [
    {
      id: 'chg-001',
      title: 'Three tiny appreciations',
      description: 'Write three small things you appreciate about each other today.',
      category: 'reassurance',
      isDaily: true,
      completedBy: [],
      createdAt: seededAt,
    },
    {
      id: 'chg-002',
      title: 'Memory placeholder prompt',
      description: 'Pick one shared memory and name a detail you want to remember.',
      category: 'memory',
      isDaily: true,
      completedBy: [],
      createdAt: seededAt,
    },
    {
      id: 'chg-003',
      title: 'One gentle question',
      description: 'Ask one question that helps you understand each other more clearly.',
      category: 'deep',
      isDaily: false,
      completedBy: [],
      createdAt: seededAt,
    },
  ],
  futurePlans: [
    {
      id: 'future-001',
      title: 'Shared Plan Placeholder',
      description: 'A generic future-plan card for testing the board layout.',
      type: 'dream',
      status: 'one-day',
      priority: 'medium',
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      id: 'future-002',
      title: 'Planned Date Placeholder',
      description: 'A neutral sample plan with no personal date or location.',
      type: 'date',
      status: 'planned',
      priority: 'high',
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      id: 'future-003',
      title: 'Private Plan Placeholder',
      description: 'A hidden sample plan for admin visibility testing.',
      type: 'promise',
      status: 'secret',
      priority: 'low',
      createdBy: 'user-owner',
      createdAt: seededAt,
      updatedAt: seededAt,
    },
  ],
  importantDates: [
    {
      id: 'imp-001',
      coupleId: 'couple-default',
      createdByUserId: 'user-owner',
      title: 'Our Anniversary',
      description: 'The day we first met and started our journey together.',
      date: '2022-06-01',
      type: 'anniversary',
      recurrence: 'yearly',
      reminderEnabled: true,
      reminderDaysBefore: 7,
      isPrivate: false,
      createdAt: seededAt,
      updatedAt: seededAt,
    },
    {
      id: 'imp-002',
      coupleId: 'couple-default',
      createdByUserId: 'user-owner',
      title: 'Birthday Wishlist Surprise',
      description: 'Some ideas I have for my birthday. Keep it secret!',
      date: '2025-10-15',
      type: 'birthday',
      recurrence: 'yearly',
      reminderEnabled: true,
      reminderDaysBefore: 3,
      isPrivate: true,
      createdAt: seededAt,
      updatedAt: seededAt,
    }
  ],
};
